openapi: 3.0.0
info:
  title: bot-unlar-ms API
  description: API para el microservicio bot-unlar-ms de la Universidad Nacional de La Rioja
  version: 1.0.0

servers:
  - url: https://api.example.com/v1

paths:
  /chat:
    post:
      summary: Procesa el mensaje del usuario
      description: Recibe el mensaje del usuario y lo procesa, devolviendo una respuesta del chatbot
      operationId: processMessage
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: string
                  description: ID del usuario
                message:
                  type: string
                  description: Mensaje del usuario
                lang:
                  type: string
                  description: C칩digo de idioma en formato ISO 639-1
                  default: "es"
      responses:
        '200':
          description: Respuesta exitosa del chatbot
          content:
            application/json:
              schema:
                type: object
                properties:
                  response:
                    type: string
                    description: Respuesta del chatbot al mensaje del usuario
        '400':
          description: Error en la solicitud (par치metros incorrectos o faltantes)
        '401':
          description: Error de autenticaci칩n (token inv치lido o expirado)
        '500':
          description: Error interno del servidor

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
